### ISSUE TITLE
support firebase 7 with @angular/fire

### ISSUE THREAD

**Issue by johanchouquet** [angular/angularfire#2189]
Hi,

This is not a bug but a feature request.

In order to benefit the latest goodies of Firebase for the web (remote config, analytics and extensions), it'd be so great that @angular/fire would support Firebase 7.

Do you plan on working on that anytime soon ?

Thanks a lot.

**Comment by jamesdaniels** [comment]
WIP here #2187. Let me know what you think of the API.

**Comment by johanchouquet** [comment]
Hi @jamesdaniels , i'll do that. Awesome!

**Comment by Dan203** [comment]
So when is this going to go live? I would like to use some of these features in a new app I'm working on but it doesn't look like there is a release with this change yet.

**Comment by doczoidberg** [comment]
API looks good for me

**Comment by jamesdaniels** [comment]
@Dan203 I'll have a release in the next week. Taking a couple days of R&R after getting back from the Firebase Summit roadshow.

**Comment by doczoidberg** [comment]
@jamesdaniels any news?

**Comment by tgangso** [comment]
when can we expect this?

**Comment by almothafar** [comment]
So, any news about the release, it was expected to have it from about 2 weeks ago.

**Comment by jamesdaniels** [comment]
I've fixed the zone.js issues that were plaguing #2187. Turns out they were affecting the 5.2.1 release too, if you upgraded Firebase and ignored the peer warning (1c3e423). I've fixed these in 5.2.3 ([let's just skip over 5.2.2...](https://github.com/angular/angularfire/releases/tag/5.2.2) 😇) 

With that out of the way, I'll continue to work on the new features.

**Comment by tgangso** [comment]
@jamesdaniels 

Great, would you mind elaborating on the zone.js issues, what problem did it cause for end users?

**Comment by johanchouquet** [comment]
Great news! Thanks a lot @jamesdaniels !

**Comment by jamesdaniels** [comment]
@tgangso if you injected either `FirebaseApp` with Firebase v7 or brought in `AngularFirePerformanceModule` then your app would never stabilize, disrupting service workers, making SSR impossible, and leading to general (but subtle) mayhem 😛 

@johanchouquet I think ng 9 and Ivy will influence us moving forward but I don't foresee any breaks for the time being. I've started including basic ng 9 tests and I have a PR in which I've moved over to ngc building the library but haven't finished due to red tests. I'll be prioritizing that after 5.3. For risk of breaking I might just include that in version 6; which I foresee as 99% API compatible. I'll just be dropping compatibility with older Angular, Typescript, and Firebase versions.

**Comment by tgangso** [comment]
@jamesdaniels thanks for fixing it, I have been using both and have had some weird subtle issues, maybe this will fix it.

**Comment by johanchouquet** [comment]
> @johanchouquet I think ng 9 and Ivy will influence us moving forward but I don't foresee any breaks for the time being. I've started including basic ng 9 tests and I have a PR in which I've moved over to ngc building the library but haven't finished due to red tests. I'll be prioritizing that after 5.3. For risk of breaking I might just include that in version 6; which I foresee as 99% API compatible. I'll just be dropping compatibility with older Angular, Typescript, and Firebase versions.

Releaved to know that our code base would likely not be too much disturbed. Thanks a lot for the clarifications @jamesdaniels !

**Comment by matheo** [comment]
Thanks a lot @jamesdaniels 
I've been missing the 5.3 release :)
