### ISSUE TITLE
AngularFirebaseFunctions [Uncaught Error: Response is not valid JSON object.]

### ISSUE THREAD

**Issue by LeviBarker** [angular/angularfire#2356]
**Angular:** 9.0.2

**Firebase:** 5.5.7

**AngularFire:** 5.4.2

### How to reproduce these conditions

**Steps to set up and reproduce**

**index.js** Firebase Functions
```
   exports.sendEmail = functions.https.onCall(async (data, context) => {
    return await sendEmail(data);
   });
```

**subscription-overview.component.ts** Angular
```
import { Component, OnInit } from '@angular/core';
import { AngularFireFunctions } from '@angular/fire/functions';

@Component({
  selector: 'app-subscription-overview',
  templateUrl: './subscription-overview.component.html',
  styleUrls: ['./subscription-overview.component.scss']
})
export class SubscriptionOverviewComponent implements OnInit {

  sendEmailCallable: any;

  constructor(private fns: AngularFireFunctions) {
   this.sendEmailCallable = fns.httpsCallable('sendEmail');
  }

  sendEmail(){
    this.sendEmailCallable({
        "recipients": ["email@test.com"],
        "subject": "Test subject",
        "body": "Test body"
    }).subscribe(response => {
        console.log(response);
    }, error => {
        console.error(error);
    })
  }
}
```

### Debug output

```
Uncaught Error: Response is not valid JSON object.
    at new HttpsErrorImpl (index.cjs.js:58)
    at Service.<anonymous> (index.cjs.js:543)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at fulfilled (tslib.es6.js:70)
    at ZoneDelegate.invoke (zone-evergreen.js:365)
    at Object.onInvoke (core.js:41257)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:851
```

### Expected behavior

Call to succeed.

### Actual behavior

Using AngularFirebaseFunctions works locally, but not when Angular is deployed to Firebase hosting.

> Note: This Node.js script succeeds when functions are deployed.

```
firebase.initializeApp(firebaseConfig);
const functions = firebase.functions();

const sendEmailCallable = firebase.functions().httpsCallable('sendEmail');
sendEmailCallable({data: {
    recipients: ['email@test.com'],
    subject: 'Test subject',
    body: 'test body'
}}).then(result => console.log(result));
```

**Comment by leandroz** [comment]
Same here, it works correctly locally but not with the rewrite for hosting.

```
const callable = this.fns.httpsCallable('updateViews');
callable({productId: this.product.id})
    .toPromise()
    .then(console.log)
    .catch(console.warn);
```

```
exports.updateViews = functions.https.onCall(async (data) => {
  console.log(data); // This log do not appear in functions console
  const product = (await db.collection('products-statistics').doc(data.productId).get()).data();
  await db.collection('products-statistics').doc(data.productId).update({
    views: product?.views + 1
  });
  return {};
});
```
```
"@angular/fire": "^6.0.0",
"firebase": "^7.14.0",
```

**Comment by leandroz** [comment]
@LeviBarker ok the problem is the rewrites order, if the wildcard goes first, then the request returns index.html instead of calling the function. Let me know how it goes.

```
      "rewrites": [
        {
          "source": "/project-id/us-central1/updateViews",
          "function": "updateViews"
        },
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
```

**Comment by LeviBarker** [comment]
@leandroz Thanks for the suggestion, I’ll definitely look into it this week!

**Comment by AnyoneAtWork** [comment]
I have a similar setup which result in the exact if i deploy to firebase hosting service .

Minimalistic setup: 

**app.module.ts**
`@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireFunctionsModule,
  ],
  providers: [
    { provide: ORIGIN, useValue: 'https://project-id-beta.web.app/' },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}`

I use ORIGIN, since i need to deploy to a subhost, otherwise it would return a cors-error.

**app.component.ts**
`import { AngularFireFunctions } from '@angular/fire/functions'
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  constructor(private fns: AngularFireFunctions) {
    this.callTestFunction();
  }

  callTestFunction() {
    const callable = this.fns.httpsCallable('testfunction');
    const observable = callable({});
    observable.subscribe(console.log, console.error);
  }
}`

**Package.json**
`{
  "name": "testfunctions",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/fire": "^6.0.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "firebase": "^7.14.3",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3",
    "@angular-devkit/architect": "~0.900",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1"
  }
}
`

It is running on a node-version 12 but same error occurs on node 10

**Comment by codethatstack** [comment]
I just came across this same issue and the fix is NOT to define `ORIGIN` injection token when deploying to Firebase hosting.

This is what worked for me:
`
const ORIGIN_PROVIDER = environment.isLocal ? [{ provide: ORIGIN, useValue: 'https://project-id-beta.web.app/' }] : [];

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireFunctionsModule,
  ],
  providers: [
    ORIGIN_PROVIDER 
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
`

**Comment by codethatstack** [comment]
I just came across this same issue and the fix is NOT to define ORIGIN injection token when deploying to Firebase hosting.

This is what worked for me:

`const ORIGIN_PROVIDER = environment.isLocal ? [{ provide: ORIGIN, useValue: 'https://project-id-beta.web.app/' }] : [];

@NgModule({
declarations: [AppComponent],
imports: [
BrowserModule,
AngularFireModule.initializeApp(environment.firebase),
AngularFireFunctionsModule,
],
providers: [
ORIGIN_PROVIDER
],
bootstrap: [AppComponent],
})
export class AppModule {}
`

**Comment by jamesdaniels** [comment]
Use the `NEW_ORIGIN_BEHAVIOR` DI token and Firebase v8 to be able to ditch the path work-around. This will be the standard in the next major.

**Comment by vdiaz1130** [comment]
Did this change in 7.0.4?

![image](https://user-images.githubusercontent.com/24530571/133638829-426ae2a1-5999-4de4-b3df-9b2037394eb6.png)

**Comment by jamesdaniels** [comment]
@vdiaz1130 `NEW_ORIGIN_BEHAVIOR` is now true, no need to opt-in into the break.

**Comment by riveruniversity** [comment]
I had the same error but it worked for me when I added [rewrites ](https://firebase.google.com/docs/hosting/full-config#firebase-json_example) in the `firebase.json`.

```
"rewrites": [
      {
        "source": "/urlToCall",
        "function": "apiRequest"
      }
]
```

### Functions Side
TypeScript
```
import * as functions from 'firebase-functions'

export const apiRequest = functions.https.onCall((searchTerm: string, context: CallableContext): Promise<HttpsCallableResult> {
	const person: Person = await api.searchPeople(searchTerm)
	return { data: person }
}
```


JavaScript
```
const functions = require("firebase-functions");

exports.apiRequest = functions.https.onCall(searchTerm, context): Promise<HttpsCallableResult> {
	const person = await api.searchPeople(search)
	return { data: person }
}
```


### Client Side
Angular (TypeScript)
```
import { AngularFireFunctions } from '@angular/fire/compat/functions';
import { HttpsCallableResult } from '@angular/fire/functions';

constructor( private functions: AngularFireFunctions) {}

searchPeople(sid: string): Observable<HttpsCallableResult> {
    const callable = this.functions.httpsCallable('searchPeople');
    return callable(sid).subscribe((response: any) => console.log('searchPeople', response))
}
```
