### ISSUE TITLE
error in the new update

### ISSUE THREAD

**Issue by jacorderodiaz** [angular/angularfire#2371]
ERROR in The target entry-point "@angular/fire" has missing dependencies:
 - firebase/app

**Comment by hiepxanh** [comment]
I understand you are new one. Please follow issues template, and provide us more information, how you can reproduce the error? can you provide example repository?
copy your error log, screenshoot, and your example repository.... Or we don't know what to do with two line of description

**Comment by smarth55** [comment]
I can help because I'm seeing it, too. I was actually trying to make another repo for another issue when I ran into this. If you start a new project and run `ng add @angular/fire` the `firebase` package is not pulled in for you. So when you build, you get 
```
ERROR in The target entry-point "@angular/fire" has missing dependencies:
 - firebase/app
```
Adding the `firebase` package manually fixed it.

**Comment by christianmenz** [comment]
I have the same issue. I just followed the instructions above:
**npm install --save firebase**

Not sure what caused the issue, but it may be good to get this fixed.

**Comment by kresdjan** [comment]
Makes no sense that generating a new Angular app `ng new myfireapp` and then running the schematics `ng add @angular/fire` doesn't also install the dependencies and wire everything up correctly.
