### ISSUE TITLE
Is it possible to use Custom Token while observing a Collection?

### ISSUE THREAD

**Issue by jimisdrpc** [angular/angularfire#2419]
In few words, is it possible to add an idToken when observing/listening a Collection throw snapshotChanges or valueChanges or any other method?

With this code in Angular I can observe changes in an entire collection (transfer is my Firestore collection):

`public transfers: Observable<any[]>;
constructor(db: AngularFirestore) {
   this.transfers = db.collection('/transfer').valueChanges(); `

and with this code I can observe a specific document:

  public transfers: Observable<any[]>;
  transferCollectionRef: AngularFirestoreCollection<any>;

  constructor(db: AngularFirestore) {

    this.transferCollectionRef = db.collection<any>('transfer', ref => ref.where("id", "==", "1"));
    this.transfers = this.transferCollectionRef.snapshotChanges().map(actions => {
      return actions.map(action => {
        const data = action.payload.doc.data();// as Todo;
        const id = action.payload.doc.id;
        return { id, ...data };
      });
    });

With this curl command I can use token also but obviously I curl isn't going to keep observing. I am just pasting curl scrupt to clarify what I mean by idToken generated from a Custom Token

curl --location --request POST 'https://firestore.googleapis.com/v1/projects/firetestjimis/databases/(default)/documents:runQuery' \
--header 'Authorization: Bearer eyJh..... a valid idToken returned from 
 https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key ..... kUifgEtHT4ZXde1ehf_PIwNDx6_ZfJuQ' \
--header 'Content-Type: application/json' \
--data-raw '{
"structuredQuery": {
    "where" : {
        "fieldFilter" : { 
        "field": {"fieldPath": "id"}, 
        "op":"EQUAL", 
        "value": {"stringValue": "1"}
        }
    },
    "from": [{"collectionId": "transfer"}]
    }
}'

So, my question is: how can I use same idToken while listening a Collection?

**Comment by burdokat** [comment]
I am having the same question...
Also I can describe another scenario I was having an issue with.
For example this code will work fine:

```
import { AngularFireDatabase } from '@angular/fire/database';

@Injectable({
  providedIn: 'SomeAppRoot'
})
export class SomeService {

  constructor(
    private afDatabase: AngularFireDatabase
  ) { }

  checkSomethingInFirebaseDB( ) {
    from(this.afDatabase.object('path/to/check').valueChanges()).subscribe(
      val => { /* Do something */ },
      err => { console.warn(err); },
      () => { console.log('closed connection'); }
    );
  }
}
```

I was using authentication as described in the docs [FireBase Auth REST API](https://firebase.google.com/docs/reference/rest/auth).
I suppose there's no problem with that. Also, I was using the `"auth !== null"` rule in the db, so the user must have a valid token and I have to attach the token as a query string if I have to access the database using the http request methods.

But then, `checkSomethingInFirebaseDB()` will not work and will give a permission denied error because there's no token being retrieved by angular/fire. 

I am well aware that the current implementation of this library is to use the angular/fire/auth because it handles the token in the background, so we don't have to worry about that. The downside is that anyone that wants to use any modules in angular/fire, with said authentication rules, without permission denied errors, is that you need to force angular/fire/auth in your code. 
What if I want to use Firebase Auth REST API?

So, my question is:
Is there any way to handle the token manually or set the token to angular/fire/auth manually???

**Comment by jamesdaniels** [comment]
We currently do not support auth in SSR out of the box, I know that people have achieved this with Firebase cookie auth & I'd consider it as a possible feature in the next major release of AngularFire.
