### ISSUE TITLE
'sample' project doesn't render on IE11 (fine on everything else)

### ISSUE THREAD

**Issue by d3vtoolsmith** [angular/angularfire#2742]
**Angular:** 11

**Firebase:** 8

**AngularFire:** 6.1.4

The kitchen sink project inside 'sample' folder does not work on IE11 even with all the polyfills already included in there (doesn't render anything, no JS errors). Project runs fine on every other browser.

**Comment by rgant** [comment]
I was looking into this yesterday. This [comment describes the actual error](https://github.com/angular/angularfire/issues/2296#issuecomment-760945318)

> Unhandled Promise rejection: Cannot create property for a non-extensible object

Which I assume has to do with the Proxy pollyfill work arounds.

**Comment by jamesdaniels** [comment]
Yeah, I'm looking into the remaining issues there. I believe it to be analytics related, as if I comment that out it works in IE11. Not sure if I will be able to find the root cause in this series TBH as we have a new version of the Firebase JS SDK coming down the pipe, where with any luck, I won't need to proxy...

**Comment by rgant** [comment]
`AngularFirePerformanceModule` also results in an error.

**Comment by domiSpyro** [comment]
I think I know the reason of this bug. 

I had a perfectly working repo (on all browsers including IE11) in Angular 9 with:
- "firebase": "~7.24.0"
- "@angular/fire": "^5.4.2"

until I upgraded firebase and angular/fire packages to:
- "firebase": "~8.3.0"
- "@angular/fire": "^6.1.4"

After upgrade I get a **syntax error** in **AngularFireAuthGuard** (which has ES2015 syntax instead of es5). 

"@angular/fire": "^5.4.2" module field in [package.json](https://unpkg.com/browse/@angular/fire@5.4.2/package.json) point to [index.js](https://unpkg.com/browse/@angular/fire@5.4.2/index.js) which imports es5 version of angular/fire while "@angular/fire": "^6.1.4" module field in [package.json](https://unpkg.com/browse/@angular/fire@6.1.4/package.json) points to [fesm2015/angular-fire.js](https://unpkg.com/browse/@angular/fire@6.1.4/fesm2015/angular-fire.js), which is in ES2015 syntax.

Other packages inside @angular scope (ex: forms, core, animations etc) includes esm5 build while @angular/fire does not

**Comment by JamieLW** [comment]
We are getting the same issue as @domiSpyro too with @angular/fire. Since upgrading firebase and angular fire it no longer supports IE11.

![image](https://user-images.githubusercontent.com/5394206/114022504-c04a1280-9869-11eb-841b-36a1aabfeb8c.png)

The polyfills suggested here: https://www.npmjs.com/package/@angular/fire dont make a difference.

**Comment by Draccoz** [comment]
I can slso confirm this. `module` field in package.json isn't an official standard, so doesn't force ES5 or ES6 in the output, but please bear in mind other Angular packages use that field to reference ES5 compliant build, thus do not parse it further. As this is an angular library, please match the behavior of the rest of the stack.

**Comment by shayan-paul** [comment]
I have tried using polyfils.
    "first-input-delay": "^0.1.3",
    "proxy-polyfill": "^0.3.2",
    "whatwg-fetch": "^3.4.1"

The angular fire version is
    "@angular/fire": "^6.0.5",
    "firebase": "^7.0.0 || ^8.0.0",

ng build is working fine but the application is throwing error as syntax error in angular fire class in IE 11

**Comment by jamesdaniels** [comment]
IE 11 is slowly being dropped from our platforms starting with the new versions, I'm happy to take any simple patches if folk isolate the issues; but I'm no longer testing in IE and don't think we can provide any cycles here.
