### ISSUE TITLE
angularFire 7 entire auth module is bundled

### ISSUE THREAD

**Issue by YannicEl** [angular/angularfire#2912]
### Version info

**Angular:** 12.2.0

**Firebase:** 9.0.1

**AngularFire:** 7.0.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** node:14.7.0, chrome: 92.0.4515.159

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

https://github.com/YannicEl/angular-fire-7-lazy-loading

**Steps to set up and reproduce**

1. clone repo
2. run ```npm i```
3. run ```npm run build-stats```
4. run ```npm run sourcemap```

### Debug output

** Screenshots **

![sourcemap](https://user-images.githubusercontent.com/42739553/131517000-f8f1ce7c-3b3a-41e6-a5b0-03cce67a15da.png)

### Expected behavior

Do not bundle the entire auth module when no function is used?

### Actual behavior

Providing an Auth instance in a NgModule causes the entire Auth module (55kb) to be bundled, even though no Auth function is used anywhere. Is this intended behavior? How would one go about lazy loading only a specific auth function?

I understand that angular fire 7 does not lazy load services anymore. Does that mean the in order to lazy load, the service cannot be provided in the ``` app.module.ts ``` with ``` provideAuth(() => getAuth())```? How would one get an instance of the service then?

I do not know if this is intended behavior or if I am missing something.

**Comment by jamesdaniels** [comment]
That's not the whole of auth, you brought in those 55kb by importing & using `getAuth()`.

If you then brought in providers in a lazy-loaded module (e.g, a signin component that imported `GoogleAuthProvider`) or dynamically imported them yourself, then the additional bytes from those providers would not be on your main bundle. 

If you want to have complete control use the minimal [`initializeAuth`](https://firebase.google.com/docs/reference/js/auth.md#initializeauth) method rather than `getAuth`. That should cut it down to 29kb.

You can also completely lazy-load SDK modules and bypass Dependency Injection, however I do recommend providing at least the minimum viable auth instance at the AppModule layer, as it will make your life easier when you start using services like Firestore and Database.

**Comment by YannicEl** [comment]
My bad, sorry. I was going off the numbers from the blog post. But I guess these values are gzipped values? In the first picture firebase/auth is stated to be only 17.8 kb big.

Thanks for the clarification.

https://firebase.googleblog.com/2021/08/the-new-firebase-js-sdk-now-ga.html

**Comment by jamesdaniels** [comment]
@YannicEl no worries. The size also depends on a number of compiler settings such as target, stripping comments, etc. I'm guessing ngc isn't as aggressive as whatever builder David was using for the measurements.
