### ISSUE TITLE
upgrade to angularFire 7.0.3 and 4 new error

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire#2929]
An error after upgrading firebase & angularFire (still using the compat library :)):
Any idea?

**Angular: 12.2.0

**Firebase: 9.0.1

**AngularFire: 7.0.3 and 7.0.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
node 14
windows 10
chrome

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

error when looking in chrome devtools:
Emulator URL must start with a valid scheme (http:// or https://). (auth/invalid-emulator-scheme).
![image](https://user-images.githubusercontent.com/1098243/132399910-d42baf69-9035-4cf1-afe1-04ee1d3c5587.png)

code in app module:
![image](https://user-images.githubusercontent.com/1098243/132399958-48b91ce2-4587-4109-bccd-0659c59f9ff0.png)

**Comment by tja4472** [comment]
The format has changed. 
`['localhost', 9099]` becomes `['http://localhost:9099']`

**Comment by jamesdaniels** [comment]
@tja4472 is correct. In 7.0 we broke the `USE_EMULATOR` token for auth, instead taking it in a form that the JS SDK expects now that we have a typescript version that allows `Parameters<>`; rather than smoothing over this API inconsistency.

This seems trivial and annoying but means we no longer have to take feature requests and cut minor releases when the auth SDK adds new options to the useEmulator function.

**Comment by falk-stefan** [comment]
@tja4472 Can you take a look at https://github.com/angular/angularfire/issues/2932?

**Comment by LanderBeeuwsaert** [comment]
just for reference, changing as suggested solved the issue

**Comment by rami-alloush** [comment]
I had to use the following in my `app.module`:
```
    { provide: USE_FIRESTORE_EMULATOR, useValue: environment.useEmulators ? ['127.0.0.1', 8080] : undefined },
```
