### ISSUE TITLE
Auth Module not Working

### ISSUE THREAD

**Issue by Mahima-22** [angular/angularfire#2953]
### Version info

**Angular:**  12.0.2

**Firebase:** 9.0.2

**AngularFire:** 7.0.4

**Other (e.g. Ionic, browser):** "@ionic/core": "^5.7.0",

### How to reproduce these conditions

Auth module implemented as  described [here](https://github.com/angular/angularfire/tree/master/samples/modular/src/app/auth) 
 but this giving error 

``` TypeError: Cannot read property 'tenantId' of null```

### code

service file 

constructor(@Optional() private auth: Auth) {}

    async signInWithEmail(values) {
      return await signInWithEmailAndPassword(this.fireauth, values.email, values.password)
    }
  
  inside component 
  
    this.authSrv.signInWithEmail(values).then((resp: any) => {
                user = resp
                console.log(resp)
              }
              ).catch(err => console.log(err));

It goes to in catch section not in then with below error.

### Expected behavior

should authenticate user

### Actual behavior

 
``` TypeError: Cannot read property 'tenantId' of null```

### Quetion
For Auth module in older version we were using `AngularFireAuthModule` but in v9, we are importing nothing ?

**Comment by rajneshbiz** [comment]
Yes @Mahima-22 , the documentation isn't as clear or in depth as it could be because Firebase 9 is still so new but with time it'll surely improve. 

You need to import the Firebase AngularFireAuthModule with latest syntax that is 

```provideAuth(() => getAuth()),```

From 

`import { getAuth, provideAuth } from '@angular/fire/auth';`

Also you can remove `@Optional()` from constructor  as it now available.

Hope this help.

**Comment by Mahima-22** [comment]
Thank you @rajneshbiz 
Solution is working.
