### ISSUE TITLE
Firebases 9.9.3 breaks authentication

### ISSUE THREAD

**Issue by akshaybabloo** [angular/angularfire#3262]
### Version info

**Angular:** 14.1.3

**Firebase:** 9.9.3

**AngularFire:** 7.4.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** None

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

You can use the modular example

**Steps to set up and reproduce**

1. Upgrade your current Firebase from 9.9.2 to 9.9.3

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

```
main.ts:12 FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at getApp (index.esm2017.js:470:29)
    at getAuth (index-90ebcfae.js:9467:30)
    at angular-fire.js:227:48
    at angular-fire.js:160:59
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Zone.run (zone.js:134:43)
    at NgZone.runOutsideAngular (core.mjs:26277:28)
    at runOutsideAngular (angular-fire.js:160:35)
    at angular-fire.js:227:21
    at app.module.ts:60:30
    at angular-fire-auth.js:33:51
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Zone.run (zone.js:134:43)
    at NgZone.runOutsideAngular (core.mjs:26277:28)
    at Object.useFactory (angular-fire-auth.js:33:27)
(anonymous) @ main.ts:12
invoke @ zone.js:372
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
then @ zone.js:1461
bootstrapModule @ core.mjs:27097
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:71
(anonymous) @ main.js:2
```

** Output from `firebase.database().enableLogging(true);` **

Not using DB

** Screenshots **

None.

### Expected behavior

This error should not have come

### Actual behavior

Stops the UI to run

**Comment by spicemix** [comment]
You don't give us much to work off here, but if you're using the v9 SDK, I found

```typescript
// provideAuth(() => getAuth()), // breaks
provideAuth(() => getAuth(getApp())), // works
```

And you can use the `getApp()` for the first parameter in each of those calls for the various firebase competencies in case there is a race condition.

Of course, then you might fall into this [Component auth has not been registered yet](https://stackoverflow.com/questions/71057826/get-component-auth-has-not-been-registered-yet-when-using-firebase-authenticat) bug, but I think that may be because I'm halfway through porting and it might go away when the last of my /compat deps are purged. If not I may open an issue here on that one. People are saying it's old code lying around in node_modules or something.

**Comment by akshaybabloo** [comment]
This fixed it. Thanks.

**Comment by vkrinichansky** [comment]
@spicemix could you please help me? i have no dependencies to firebase, only angular fire, but i get **Component auth has not been registered yet** after deploying app to hosting. On local env all works fine. Maybe you have some ideas how to fix it?
