### ISSUE TITLE
Documentation is out of date and does not reflect the latest version

### ISSUE THREAD

**Issue by mdcotter** [angular/angularfire#3322]
Having difficulty navigating the new structure with the old documentation

**Comment by rubenheymans** [comment]
@lazmeister I'm stuck with the auth guards, there is not much documentation and the code I find just doesn't work with the latest's versions

**Comment by lazmeister** [comment]
@rubenheymans sent you a twitter request

**Comment by rubenheymans** [comment]
@lazmeister thanks but I can't see anything on twitter after trying a couple of times, I have no idea how twitter works, is there a different way to communicate? (Also I'm curious why anyone would even use Twitter?)

**Comment by lazmeister** [comment]
Okay no worries. What platform works for you?

**Comment by rubenheymans** [comment]
@lazmeister discord (Ruben#8145), teams (ruben.heymans@outlook.com), slack (ruben.heymans)

**Comment by SoyAaronCervantes** [comment]
@rubenheymans you're right, there aren't too much information about Auth Guard.
What I did, I started to read the Angular Fire code  and try to check what `@angular/fire/auth-guard` exports.

<img width="1150" alt="Screenshot 2023-05-22 at 17 33 54" src="https://github.com/angular/angularfire/assets/17758070/dfcd3296-03c2-437e-9bfe-7614ee786bcd">


On my job, we used it for authentication, and we use the functions that `@angular/fire/auth-guard` provides:
 - redirectLoggedInTo
 - redirectUnauthorizedTo
 
 ```ts
 // For logout workflow
   {
    path: 'logout',
    loadChildren: () => import('./signout.module').then((m) => m.SignoutModule),
    canActivate: [AuthGuard],
    data: {
      authGuardPipe: () => redirectUnauthorizedTo(['/login'])
    }
  },
  // For login workflow
  {
    path: 'login',
    canActivate: [AuthGuard],
    data: {
      authGuardPipe: () => redirectLoggedInTo([''])
     }
  }
 ```

But also, we need to check, if a user is authenticated already, from one domain to another domain.

For that case we need to create a custom function to validate if the user is authenticated

```ts
const url = 'current.domain
{
    path: 'another-route',
    canActivate: [ AuthGuard ],
    loadChildren: () => import('./content.module').then(m => m.ContentModule),
    data: {
      authGuardPipe: (next: ActivatedRouteSnapshot) => checkUserAuthentication( url, next )
    }
  }
```

This is a short version from `checkUserAuthentication`
```ts
// Check User Authentication
export const checkUserAuthentication =
  (
    currentDomain: string,
    activatedRouteSnapshot: ActivatedRouteSnapshot
  ) => pipe(
    map( (user: User) => {

      if (user !== null) { return true; }

      const token = getToken(activatedRouteSnapshot);
      if (token !== null) { return true; }

      window.location.href = `${ auth.domain }/login?redirect=${  currentDomain  }`;
      return false;
    })
  );
```

Today, and [thanks to this issue](https://github.com/angular/angularfire/issues/2136), I noticed that this functions shouldn't be working, because `authGuardPipe` expects an `AuthPipeGenerator function`, that return an `AuthPipe`, and `AuthPipe` should return an `string, boolean or any[] as an observable`.

As I said, it shouldn't be working, but it works

I hope this can help you, to understand a little bit better how to use and implement  the `AuthGuardModule`.

**Comment by davideast** [comment]
We've made a bunch of updates to the documentation and we are working to improve i in the upcoming future, so stay tuned!

**Comment by rami-alloush** [comment]
I still can't find the link to the latest docs

**Comment by lazmeister** [comment]
> I still can't find the link to the latest docs

![Image](https://github.com/user-attachments/assets/8f2cfd08-e39a-4562-9329-b766d1025d1c) https://github.com/angular/angularfire/blob/main/docs/firestore.md

**Comment by rami-alloush** [comment]
Thank you @lazmeister, my challenge is with Auth Guards or Router Guards (I'm not even sure what they are called anymore :/)

**Comment by lazmeister** [comment]
I would just check the API, There must be someone out there that posted about it, if not specify to AI which API you are using (version #) and it can give you proper instructions as well. https://github.com/angular/angularfire/blob/main/src/auth-guard/auth-guard.ts
