### ISSUE TITLE
AngularFireModule is required while Unit testing ?

### ISSUE THREAD

**Issue by sivanshkamat** [angular/angularfire#3383]
** Error Faced:** : Either AngularFireModule has not been provided in your AppModule (this can be done manually or implictly using provideFirebaseApp) or you're calling an AngularFire method outside of an NgModule (which is not supported). 

The code runs perfectly but Unit testing throws the above error:

service.ts:

```
import { Injectable } from '@angular/core';
import { from, Observable } from 'rxjs';
import {
  Auth,
  signInWithEmailAndPassword,
  authState,
  createUserWithEmailAndPassword,
  UserCredential,
} from '@angular/fire/auth';

@Injectable({
  providedIn: 'root',
})
export class AuthService {
  currentUser$ = authState(this.auth);
  constructor(private auth: Auth) {}

  signUp(email: string, password: string): Observable<UserCredential> {
    return from(createUserWithEmailAndPassword(this.auth, email, password));
  }

  login(email: any, password: any): Observable<any> {
    return from(signInWithEmailAndPassword(this.auth, email, password));
  }

  logout(): Observable<any> {
    return from(this.auth.signOut());
  }
}

```

### Version info

**Angular:** 16.0.0

**Firebase:** 9.22.1

**AngularFire:** 7.6.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
![image](https://github.com/angular/angularfire/assets/54890522/db99f6a7-60cb-4250-8b6c-a1f34f5b6faa)

**Comment by pfpoujol** [comment]
Need help for this too!

**Comment by davideast** [comment]
Forgive me! I'm brushing back up on this library after a long time away. AFAIK, you still need to include the `AngularFireModule` because it's [required for initializing the Firebase App instance](https://github.com/angular/angularfire/blob/master/src/compat/firebase.app.module.ts#L51C10-L51C23) (at least for non-standalone apps).

This has to be done to [avoid initializing Firebase within Angular's Zone](https://github.com/angular/angularfire/blob/master/src/compat/firebase.app.module.ts#L21) and running into change detection issues.

I'm going to close this issue because the solution is to include the `AngularFireModule` within your unit tests and I recommend using the Emulator Suite to fully run offline as well. If you run into anymore issues feel free to tag me in this issue and I'll respond or reopen if needed.
