### ISSUE TITLE
AngularFire v18 ng serve error when using zoneless change detection: Zone is not defined

### ISSUE THREAD

**Issue by anisabboud** [angular/angularfire#3537]
### Version info

**Angular:** 18.0.0
**AngularFire:** 18.0.0
**Firebase:** 10.12.1

### How to reproduce these conditions

Follow the Angular 18 guide to enable zoneless:
1. Add `provideExperimentalZonelessChangeDetection()` to `providers`.
2. remove `zone.js` from polyfills in `angular.json`.
3. Run `ng serve`

https://blog.angular.dev/angular-v18-is-now-available-e79d5ac0affe

### Debug output

**Error in the terminal** `Zone is not defined`

```bash
/myproject/node_modules/@angular/fire/fesm2022/angular-fire.mjs:101
    this.outsideAngular = ngZone.runOutsideAngular(() => new ɵZoneScheduler(Zone.current));
                                                                            ^


ReferenceError: Zone is not defined
    at eval (/myproject/node_modules/@angular/fire/fesm2022/angular-fire.mjs:101:77)
    at input (/myproject/node_modules/@angular/core/fesm2022/core.mjs:15827:16)
    at _ɵAngularFireSchedulers (/myproject/node_modules/@angular/fire/fesm2022/angular-fire.mjs:101:34)
    at Object._ɵAngularFireSchedulers_Factory (/myproject/node_modules/@angular/fire/fesm2022/angular-fire.mjs:106:12)
    at eval (/myproject/node_modules/@angular/core/fesm2022/core.mjs:3233:47)
    at runInInjectorProfilerContext (/myproject/node_modules/@angular/core/fesm2022/core.mjs:871:9)
    at R3Injector.hydrate (/myproject/node_modules/@angular/core/fesm2022/core.mjs:3232:21)
    at R3Injector.get (/myproject/node_modules/@angular/core/fesm2022/core.mjs:3095:33)
    at injectInjectorOnly (/myproject/node_modules/@angular/core/fesm2022/core.mjs:1106:40)
    at ɵɵinject (/myproject/node_modules/@angular/core/fesm2022/core.mjs:1112:42)

Node.js v20.13.1
```

### Expected behavior

AngularFire/`ng serve` should work with the new zoneless change detection introduced in Angular v18.
https://angular.dev/guide/experimental/zoneless

### Actual behavior

`ng serve` crashes when opening `localhost:4200`.

**Comment by spock123** [comment]
@jamesdaniels did I say you rock? you do

I was thinking.. what happens if we just made a global Zone object that monkey patches the zone methods? Just empty stuff. Would that not work? Literally 15 lines of should be more than enough. Do you. think that would work?

**Comment by duxor** [comment]
The same topic is here: https://github.com/angular/angularfire/issues/3494

**Comment by kiakahaDZ** [comment]
any solution found plz i have the same issue

**Comment by Benzilla** [comment]
Eagerly waiting on this - AngularFire is the only package currently stopping us from going zoneless

**Comment by wis-dev** [comment]
@jamesdaniels any update about this? Maybe some release date.
I'm exiting to go Zoneless with Firebase 🔥

**Comment by Benzilla** [comment]
Slightly off-topic, but if you're trying to go Zoneless, you're probably doing it for performance gains.

I went through the process of converting my entire SSR Angular 18 app to use signals for zoneless change detection and was waiting on AngularFire to support zoneless so I could finally remove zone.js from polyfills to "officially" go completely zoneless.

In the process I realised that I no longer actually used any of the [benefits of AngularFire](https://github.com/angular/angularfire?tab=readme-ov-file#angularfire), and decided to move over to the official Firebase package. This let my project go zoneless, and also reduces bundle size further and removes dependencies.

It's not something I'd considered because everytime I've built with Angular & Firebase, AngularFire was the first thing I reached for, but it seems maybe with these latest Angular developments it's not as needed? Either way, I've loved using this package and built some awesome stuff with it - thanks for all the support and work on it.

**Comment by anisabboud** [comment]
@Benzilla can you please elaborate on the steps this migration entails?

For example, what's the replacement for the AngularFire initialization in [`app.config.ts`](https://github.com/angular/angularfire#example-use)?
```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideFirebaseApp(() => initializeApp({ ... })),
    provideFirestore(() => getFirestore()),
    provideAuth(() => getAuth()),
    provideFunctions(() => getFunctions()),
    provideStorage(() => getStorage()),
    provideAppCheck(() => ...),
    ...
  ],
  ...
})
```

**Comment by spock123** [comment]
@Benzilla  agree, I am looking to do the same, lost faith unfortunately...

**Comment by muhamedkarajic** [comment]
> 1. provideExperimentalZonelessChangeDetection

Some kind of problem like this is by me as well.

**Comment by muhamedkarajic** [comment]
Can someone help me I have following error:

Error: NG0908: In this configuration Angular requires Zone.js


```ts
import { enableProdMode, isDevMode, provideExperimentalZonelessChangeDetection } from "@angular/core";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { AppModule } from './app/app.module';

const providers: any[] = [
  provideExperimentalZonelessChangeDetection(),
];

if (!isDevMode()) {
  enableProdMode();
}

platformBrowserDynamic(providers)
  .bootstrapModule(AppModule)
  .catch(err => console.error(err));
```

When I keep zone.js in polyfills then it works. I also have @angular/localize/init in polyfills.

Any help?

**Comment by Benzilla** [comment]
> @Benzilla can you please elaborate on the steps this migration entails?
> 
> For example, what's the replacement for the AngularFire initialization in [`app.config.ts`](https://github.com/angular/angularfire#example-use)?
> 
> ```ts
> export const appConfig: ApplicationConfig = {
>   providers: [
>     provideFirebaseApp(() => initializeApp({ ... })),
>     provideFirestore(() => getFirestore()),
>     provideAuth(() => getAuth()),
>     provideFunctions(() => getFunctions()),
>     provideStorage(() => getStorage()),
>     provideAppCheck(() => ...),
>     ...
>   ],
>   ...
> })
> ```

Despite AngularFire's docs, I don't think this is a good way to initialise Firebase or AngularFire anymore, and that they should be initialised in injectable services. Otherwise you are always including AngularFire / Firebase in your main bundle every single time which increases your initial chunk file transfer size and is bad for core web vitals. 

Angular states this in [their docs](https://angular.dev/guide/di/dependency-injection#preferred-at-the-application-root-level-using-providedin) that this is the preferred way, and also states its good for tree shaking etc.

Anecdotally initialising them in services reduced my initial chunk file estimated transfer size from 209.78 kB down to 94.27 kB (over 50%!) and has shown a positive improvement to core web vitals. I think maybe the AngularFire docs shouldn't state [initialising in ApplicationConfig](https://github.com/angular/angularfire?tab=readme-ov-file#example-use) is a good thing to do anymore? 

In my project I have separate services:

- database.service.ts for Firestore
- storage.service.ts for Firebase Storage
- api.service.ts for Firebase Functions
- auth.service.ts for Firebase Auth
- analytics.service.ts for Firbase Anaytics

In the constructor of each service I initialise firebase in a similar pattern, for example for Database:

```ts
import { Injectable } from '@angular/core';
import { initializeApp } from "firebase/app";
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root'
})
export class DatabaseService {

  private firestore : any;

  constructor(){
    const app = initializeApp(environment.firebase);
    this.firestore = getFirestore(app);
    if (!environment.production) {
      if(!this.firestore._settingsFrozen){ //Prevents initialising the emulator twice on SSR.
        connectFirestoreEmulator(this.firestore, 'localhost', 8080);
      }
    }
  }
}
```

For Auth
```ts
import { Injectable } from '@angular/core';
import { getAuth, connectAuthEmulator } from 'firebase/auth';
import { initializeApp } from "firebase/app";
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root'
})
export class AuthProviderService {

  public auth: any;

  constructor(){
    const app = initializeApp(environment.firebase);
    this.auth = getAuth(app);
    if (!environment.production) {
      connectAuthEmulator(this.auth, 'http://localhost:9099', { disableWarnings: true })
    }
  }
}
```

I can then just import these services into any component and access the firebase objects, and Angular should optimise via the builder and tree shaking.

I struggled like @spock123 to find examples for Angular + official Firebase package online, as if you Google Angular + Firebase this package dominates the SERPs, so I'm not sure if this is the best way to do things - but I've been running it in a production app for a week now with no problems and improved performance overall.

**Comment by LanderBeeuwsaert** [comment]
@Benzilla ooooh that's a really interesting approach for lazy loading the packages.
We have similar services, as well as some landing & manual pages that don't need any firebase functionality.
So your solution is great for that!
Too bad indeed there is no guidance/documentation from angularFire about this.

**Comment by jits** [comment]
Give the conversations about using Firebase directly, without AngularFire, I hope folks don't mind me promoting the approach I've taken for the FullStacksDev Angular and Firebase tech stack: https://github.com/FullStacksDev/angular-and-firebase-template

You can get a quick overview of how I've set this up: https://github.com/FullStacksDev/angular-and-firebase-template/blob/main/ARCHITECTURE.md#app-accessing-firebase-services-from-the-angular-app. I then use [`rxfire`](https://github.com/FirebaseExtended/rxfire) (which AngularFire uses under the hood) directly in my services (to fit nicely with RxJS). Happy to take more questions etc. in the repo I linked to, if folks are interested.

**Comment by IsmaelBembo** [comment]
@Benzilla 
> In the constructor of each service I initialise firebase in a similar pattern, for example for Database:

I've been trying to do this for a long time before encountering your comment, which it looks like it should work but I can't get rid of this error:

![image](https://github.com/user-attachments/assets/42328dbb-e76d-4462-a366-a751ed851c80)

This is my current state:

![image](https://github.com/user-attachments/assets/13b07f6e-dcfc-4632-ad98-e134d9a76070)

![image](https://github.com/user-attachments/assets/f871a337-9602-4aee-ad9a-a4a29bea1f62)

Any ideas?

**Comment by dalenguyen** [comment]
> @IsmaelBembo You need to switch from AngularFire to the regular firebase package. @Benzilla Your approach doesn't seem to work well with SSR. For some reason, during SSR, the getDocs (replacement for collectionData) freezes completely. Had to switch back to AngularFire for that reason.
> 
> In general though: Maybe don't completely hijack this issue.

I think you need to wrap it inside `afterNextRender` for it to work with SSR.

**Comment by Benzilla** [comment]
> @Benzilla Your approach doesn't seem to work well with SSR. For some reason, during SSR, the getDocs (replacement for collectionData) freezes completely. Had to switch back to AngularFire for that reason.

@ciriousjoker Should work fine with SSR (my app is fully SSR).

You need to make sure your app is zoneless, and is using ExperimentalPendingTasks for SSR: https://angular.dev/api/core/ExperimentalPendingTasks

**Comment by riya-amemiya** [comment]
Is there any progress on this?
I'm looking forward to Angular Fire from Zoneless!

**Comment by spock123** [comment]
> Is there any progress on this? I'm looking forward to Angular Fire from Zoneless!

I don't think this project is maintained properly any longer. If I were you I would migrate (if possible) to use native Firebase SDK, as it is now fully usable when you are using Zoneless.

There are a few tricks to get it set up (see this thread for suggestions, involving services to set up different Firebase features). I understand that for large projects it might be hard to migrate due to a different (and not as elegant) syntax. But it's worth it imho.

It's a shame, this library is cool but it seems nobody really did any serious developments on it (other than bumping dependencies) for many months. A pity indeed.

**Comment by jamesdaniels** [comment]
Zoneless support is now in the RCs, we'll release final after the new year https://github.com/angular/angularfire/releases
